### ISSUE TITLE
How to use placeholders?

### ISSUE THREAD

**Issue by hmpf** [oscarotero/Gettext#125]
I can't figure out how to use placeholders. In ordinary gettext it's with sprintf: `sprintf(_('This is a %s string'), 'fine');`. Is that still so with this gettext? Could some examples be added to the docs?

**Comment by oscarotero** [comment]
The last paragraph of [Usage example](https://github.com/oscarotero/Gettext#usage-example) contains an example of this.

Basically, `sprintf` is used inside the functions if you provide extra arguments. For example:

```php
// __() is a simple translation that accepts one argument
echo __('This is a fine string');

// but if you provide more arguments, they will be used as placeholder replacements:
echo __('This is a %s string', 'fine'); 

//The same with the rest of the funcions, for example for plurals:
echo n__('one user', 'many users', count($users));
echo n__('%s user', '%s users', count($users), count($users));
```

**Comment by hmpf** [comment]
Is there a way to send in a hash? array(key1 => value1, key2 => value2)

**Comment by jaimeperez** [comment]
¡Hola Óscar!

We are discussing here a couple of issues that we see, and we would like to have your input on how to solve them:

1. Using _printf_ formatters is tricky because it fixes the order of the replacements. If a translation needs to change the order of the replacements (which is quite common), those will be inverted as their order is fixed in the resulting translation. The only way to resolve that would be to use named placeholders, so that replacements can also have a name and that way you know **where** you need to put them.
2. Two equal strings could generate different strings to be translated. Say you have a _twig_ template with a string you want to translate, having one replacement. Applying the _twig_ extractor to generate a `.po` file would generate one string. Now, if we use a PHP extractor to extract the exact same string from a PHP file, that could generate a different string in the `.po` if the placeholders are treated differently. Am I right on this? If so, how could we avoid it?

¡Muchas gracias!

**Comment by mlocati** [comment]
> Using printf formatters is tricky because it fixes the order of the replacements

You can change the arguments order by using numbered arguments.
For instance, you can write a string like
`Hi %1$s, welcome to %2$s`
You can translate it as
`Benvenuto a %2$s, %1$s`

> Two equal strings could generate different strings to be translated

That's why it's a good practice to use contexts. Two English strings with the same text but different contexts can be translated in two different ways.

**Comment by oscarotero** [comment]
@hmpf You cannot use key/value pairs. But you can use a numerical array instead different arguments because [internally](https://github.com/oscarotero/Gettext/blob/master/src/translator_functions.php#L22) uses `vsprintf`. For example:

```php
echo __('This is a %s %s', 'fine', 'string');
//is equivalent to:
echo __('This is a %s %s', ['fine', 'string']);
```

¡Hola @jaimeperez!

`sprintf` allows to change the order of the arguments, just need to define the position usin `n$` just after `%`, as you can see in the 3º/4º examples of [sprintf](http://php.net/manual/en/function.sprintf.php)

```php
echo __('This is a %1$s %2$s', 'fine', 'string'); //This is a fine string
echo __('This is a %2$s %1$s', 'fine', 'string'); //This is a string fine
```

**Comment by oscarotero** [comment]
@mlocati you're faster than me 😄

**Comment by hmpf** [comment]
Regarding point 2 that @jaimeperez mentioned, the format of the placeholder is different in twig and with *printf. `{{ foo }}` vs. `%s`. So if the same string is used both inside and outside of templates, it might lead to two different strings to lookup in the translation-database.

**Comment by oscarotero** [comment]
Ok, if I understand correctly, in a project mixing php and twig, there could be a case where a string can be defined as `Welcome, %s` and `Welcome, {{ username }}`, right?

In that case, two solutions come to my mind:

* Treat them as different texts
* Use custom functions in php supporting twig placeholders  `echo __('Welcome {{ username }}, ['username' => $username]) `

**Comment by jaimeperez** [comment]
Thanks for the help guys!

I'd definitely prefer to have two strings that are equal except for the placeholders for replacements, to translate into the same string in the translation database, but I can live with that if it happens, I don't think that's a show stopper.
